# Generated by Django 4.1.3 on 2022-11-21 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('subtitulo', models.CharField(max_length=100, verbose_name='Subtitulo')),
                ('categoria', models.CharField(choices=[('cuidados', 'CUIDADOS'), ('alimentación', 'ALIMENTACION'), ('entretenimiento', 'ENTRETENIMIENTO')], default='-------', max_length=30, verbose_name='Categoria')),
                ('contenido', models.CharField(max_length=255, verbose_name='Contenido')),
                ('fecha', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Creacion')),
                ('autor', models.CharField(max_length=100, verbose_name='Autor')),
            ],
        ),
    ]
