# Generated by Django 4.1.3 on 2022-11-23 05:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categoria',
            field=models.CharField(choices=[('vacio', '------------------'), ('cuidados', 'Cuidados'), ('alimentación', 'Alimentación'), ('entretenimiento', 'Entretenimiento')], default='vacio', max_length=30, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='post',
            name='contenido',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
