# Generated by Django 4.1.3 on 2022-11-25 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppBlog', '0002_alter_post_categoria_alter_post_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='categoria',
            field=models.CharField(choices=[('vacio', '-----------------'), ('cuidados', 'Cuidados'), ('alimentación', 'Alimentación'), ('entretenimiento', 'Entretenimiento')], default='vacio', max_length=30, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Subtitulo'),
        ),
    ]
