# Generated by Django 4.1.3 on 2022-11-25 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0003_alter_post_autor_alter_post_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='autor',
            field=models.CharField(max_length=100, verbose_name='Autor'),
        ),
    ]
